### ISSUE TITLE
use modding sdk

### ISSUE THREAD

**Issue by yfthbr** [tetris245/tetris245#1]
https://github.com/Jomshir98/bondage-club-mod-sdk

the easiest way to ensure compatibility with other addons

**Comment by huzpsb** [comment]
Though provides some useful apis,but not that irreplaceable.Plus js files that were compiled from ts can take pains to understand.Maybe not worth the struggle.

**Comment by Tarram1010** [comment]
I have to agree with Sid on this. For a addon such as QAM, that touches mostly everything in the club, compatibility should be the main concern.

**Comment by huzpsb** [comment]
> I have to agree with Sid on this. For a addon such as QAM, that touches mostly everything in the club, compatibility should be the main concern.

If the compatibility is the major concern, no API should be written in ts. It is a painful and meaningless work to call anything non-native from JavaScript. Still I'd appreciate if you can make a middleware written in JS to support the mod-sdk written by Jomshir98. Only by doing so you're providing a possible way to achieve compatibility.

**Comment by tetris245** [comment]
At the moment I make a long break in QAM development. If I come back to coding, I will use probably a different approach. I think a 'modSDK'ed version will be under another name, but I don't have yet choosen a name, and I will not decide before Spring.

There are so many things to say about compatibility. From my point of view, BCX triggers too many warning or error messages, some are justified, some are just the mirror of a too strict conception. Besides, a real debugging mode should be off by default, what's the case in Kinky Dungeon for example. Only people who want to report issues should enable this mode.

**Comment by tetris245** [comment]
ULTRAbc 1.0 is available 🙂 - Enjoy!
https://github.com/tetris245/ULTRAbc

ULTRAbc is a modSDK version of QAM, providing better compatibility with other add-ons, especially BCX and FBC.
This first version does not have all QAM commands, but a big part of them is already available.
Note the new command /uhelp to access the general menu of ULTRAbc help.
More info on the ULTRAbc Wiki: https://github.com/tetris245/ULTRAbc/wiki

Link to the ULTRAbc loader: https://tetris245.github.io/ultrabc.github.io/ULTRAbcloader.js
Link to the ULTRAbc bookmark: https://tetris245.github.io/ultrabc.github.io/ULTRAbcbookmark.js
